name: Deploy to EC2
    
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: EC2 commands
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PEM }}
            script: |
                cd motiiv-server
                git pull origin dev
                npm install
                pm2 restart motiiv-server
                
